//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olwen_2._0._0.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public string NameLogin { get; set; }
        public string PassWord { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public Nullable<int> Role { get; set; }
        public Nullable<bool> Sex { get; set; }
        public Nullable<int> EmpID { get; set; }
        public byte[] Avatar { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
